import { createHmac, timingSafeEqual } from 'crypto';
import { CoreApiClient } from 'twenty-client-sdk/core';
import { defineLogicFunction } from 'twenty-sdk/define';
import type { RoutePayload } from 'twenty-sdk/logic-function';

import { BookingStatus } from '../objects/booking.object';

// Cal.com signs each delivery: x-cal-signature-256 = HMAC_SHA256(secret, rawBody).
const SIGNATURE_HEADER = 'x-cal-signature-256';

// Reject oversized bodies before parsing (DoS / storage-exhaustion guard).
const MAX_BODY_BYTES = 64 * 1024;
// Field length caps for untrusted, signed input written to the CRM.
const MAX_TITLE = 500;
const MAX_NAME = 255;
const MAX_EMAIL = 320; // RFC 5321
const MAX_URL = 2048;

// Map Cal.com triggerEvent -> Booking.status. Anything unmapped is ignored.
export const STATUS_FOR_EVENT: Readonly<Record<string, BookingStatus>> = {
  BOOKING_CREATED: BookingStatus.SCHEDULED,
  BOOKING_REQUESTED: BookingStatus.SCHEDULED,
  BOOKING_RESCHEDULED: BookingStatus.SCHEDULED,
  BOOKING_PAID: BookingStatus.SCHEDULED,
  BOOKING_CANCELLED: BookingStatus.CANCELLED,
  BOOKING_REJECTED: BookingStatus.CANCELLED,
  MEETING_ENDED: BookingStatus.COMPLETED,
};

type CalAttendee = { email?: string; name?: string };
type CalBookingPayload = {
  uid?: string;
  title?: string;
  startTime?: string;
  endTime?: string;
  attendees?: CalAttendee[];
  organizer?: { email?: string; name?: string };
  location?: string;
  videoCallData?: { url?: string };
  metadata?: { videoCallUrl?: string };
  rescheduleUid?: string;
};
type CalWebhookBody = { triggerEvent?: string; payload?: CalBookingPayload };

// The genql client is generated by `yarn twenty dev:build`, so its selection
// objects are untyped here. Confine that to this minimal surface.
type GraphqlClient = Pick<CoreApiClient, 'query' | 'mutation'>;
type BookingRef = { id: string; status?: string };

export type HttpJsonResponse = {
  statusCode: number;
  headers: Record<string, string>;
  body: string;
};

const jsonResponse = (
  statusCode: number,
  body: Record<string, unknown>,
): HttpJsonResponse => ({
  statusCode,
  headers: { 'content-type': 'application/json' },
  body: JSON.stringify(body),
});

// Reconstruct the exact bytes Cal.com signed (handles base64 transport encoding).
export const decodeRawBody = (
  event: Pick<RoutePayload, 'rawBody' | 'isBase64Encoded'>,
): string => {
  const raw = event.rawBody ?? '';
  if (event.isBase64Encoded && raw) {
    return Buffer.from(raw, 'base64').toString('utf8');
  }
  return raw;
};

export const verifySignature = (
  rawBody: string,
  signature: string | undefined,
  secret: string | undefined,
): boolean => {
  if (!signature || !secret) return false;
  const expected = createHmac('sha256', secret).update(rawBody, 'utf8').digest('hex');
  const provided = signature.trim().toLowerCase();
  const a = Buffer.from(expected, 'utf8');
  const b = Buffer.from(provided, 'utf8');
  // Length check first: timingSafeEqual throws on unequal lengths.
  if (a.length !== b.length) return false;
  return timingSafeEqual(a, b);
};

export const truncate = (value: string | undefined, max: number): string | undefined => {
  if (value === undefined) return undefined;
  return value.length > max ? value.slice(0, max) : value;
};

// Conservative single-line email shape check; also bounds length.
export const isValidEmail = (email: string | undefined): email is string =>
  !!email && email.length <= MAX_EMAIL && /^[^@\s]+@[^@\s]+\.[^@\s]+$/.test(email);

export const splitName = (full?: string): { firstName: string; lastName: string } => {
  const parts = (full ?? '').trim().split(/\s+/).filter(Boolean);
  if (parts.length === 0) return { firstName: '', lastName: '' };
  return {
    firstName: (parts[0] ?? '').slice(0, MAX_NAME),
    lastName: parts.slice(1).join(' ').slice(0, MAX_NAME),
  };
};

export const resolveMeetingUrl = (p: CalBookingPayload): string | undefined => {
  const candidate = p.videoCallData?.url ?? p.metadata?.videoCallUrl ?? p.location;
  if (!candidate || !/^https?:\/\//i.test(candidate)) return undefined;
  return truncate(candidate, MAX_URL);
};

// Don't let a stale/replayed event un-complete a finished booking.
export const reconcileStatus = (
  current: string | undefined,
  desired: BookingStatus,
): BookingStatus =>
  current === BookingStatus.COMPLETED ? BookingStatus.COMPLETED : desired;

// Best-effort: find the attendee Person by primary email, creating one if absent.
// Returns the personId to link, or undefined (booking is still recorded).
const resolvePointOfContactId = async (
  client: GraphqlClient,
  attendee: CalAttendee | undefined,
): Promise<string | undefined> => {
  const email = attendee?.email?.trim().toLowerCase();
  if (!isValidEmail(email)) return undefined;

  try {
    const found = (await client.query({
      people: {
        __args: { filter: { emails: { primaryEmail: { eq: email } } }, first: 1 },
        edges: { node: { id: true } },
      },
    } as never)) as { people?: { edges?: { node?: { id?: string } }[] } };
    const existingId = found?.people?.edges?.[0]?.node?.id;
    if (existingId) return existingId;

    const { firstName, lastName } = splitName(attendee?.name);
    const created = (await client.mutation({
      createPerson: {
        __args: {
          data: { name: { firstName, lastName }, emails: { primaryEmail: email } },
        },
        id: true,
      },
    } as never)) as { createPerson?: { id?: string } };
    return created?.createPerson?.id;
  } catch (error) {
    console.warn('cal-webhook: could not resolve point of contact', error);
    return undefined;
  }
};

const findBookingByUid = async (
  client: GraphqlClient,
  uid: string,
): Promise<BookingRef | undefined> => {
  const found = (await client.query({
    bookings: {
      __args: { filter: { calBookingUid: { eq: uid } }, first: 1 },
      edges: { node: { id: true, status: true } },
    },
  } as never)) as {
    bookings?: { edges?: { node?: { id?: string; status?: string } }[] };
  };
  const node = found?.bookings?.edges?.[0]?.node;
  return node?.id ? { id: node.id, status: node.status } : undefined;
};

const updateBooking = (client: GraphqlClient, id: string, data: Record<string, unknown>) =>
  client.mutation({ updateBooking: { __args: { id, data }, id: true } } as never);

// Pure core: given a verified, parsed Cal.com payload, upsert the Booking.
// Separated from transport so it can be unit-tested with a mock client.
export const upsertBooking = async (
  client: GraphqlClient,
  triggerEvent: string,
  payload: CalBookingPayload,
): Promise<HttpJsonResponse> => {
  const uid = payload.uid;
  if (!uid) return jsonResponse(400, { error: 'missing payload.uid' });

  const desired = STATUS_FOR_EVENT[triggerEvent];
  if (!desired) return jsonResponse(200, { ignored: triggerEvent });

  // Reschedules can arrive under a fresh uid; adopt the prior record if present.
  const existing =
    (await findBookingByUid(client, uid)) ??
    (payload.rescheduleUid
      ? await findBookingByUid(client, payload.rescheduleUid)
      : undefined);

  const pointOfContactId = await resolvePointOfContactId(
    client,
    payload.attendees?.[0] ?? payload.organizer,
  );

  // Only map fields Cal.com owns — never touch reminder flags here, so reminder
  // automations that already fired aren't reset on a later update.
  const data: Record<string, unknown> = {
    name: truncate(payload.title, MAX_TITLE) ?? `Booking ${uid}`.slice(0, MAX_TITLE),
    calBookingUid: uid.slice(0, MAX_TITLE),
    status: reconcileStatus(existing?.status, desired),
  };
  if (payload.startTime) data.startsAt = payload.startTime;
  if (payload.endTime) data.endsAt = payload.endTime;
  const meetingUrl = resolveMeetingUrl(payload);
  if (meetingUrl) data.meetingUrl = meetingUrl;
  if (pointOfContactId) data.pointOfContactId = pointOfContactId;

  let bookingId = existing?.id;
  if (bookingId) {
    await updateBooking(client, bookingId, data);
  } else {
    try {
      const created = (await client.mutation({
        createBooking: { __args: { data }, id: true },
      } as never)) as { createBooking?: { id?: string } };
      bookingId = created?.createBooking?.id;
    } catch (error) {
      // Likely a unique-index race on calBookingUid: the row now exists — update it.
      const raced = await findBookingByUid(client, uid);
      if (!raced) throw error;
      await updateBooking(client, raced.id, data);
      bookingId = raced.id;
    }
  }

  return jsonResponse(200, { ok: true, bookingId, status: data.status, triggerEvent });
};

export const handler = async (event: RoutePayload): Promise<HttpJsonResponse> => {
  const secret = process.env.CAL_WEBHOOK_SECRET;
  if (!secret) {
    console.error('cal-webhook: CAL_WEBHOOK_SECRET is not configured');
    return jsonResponse(500, { error: 'webhook secret not configured' });
  }

  const rawBody = decodeRawBody(event);
  if (!rawBody) return jsonResponse(400, { error: 'empty body' });
  if (Buffer.byteLength(rawBody, 'utf8') > MAX_BODY_BYTES) {
    return jsonResponse(413, { error: 'payload too large' });
  }

  const signature = event.headers[SIGNATURE_HEADER];
  if (!verifySignature(rawBody, signature, secret)) {
    return jsonResponse(401, { error: 'invalid signature' });
  }

  // Parse the verified bytes (not event.body) so we act on exactly what was signed.
  let parsed: CalWebhookBody;
  try {
    parsed = JSON.parse(rawBody) as CalWebhookBody;
  } catch {
    return jsonResponse(400, { error: 'invalid JSON body' });
  }

  try {
    return await upsertBooking(
      new CoreApiClient(),
      parsed.triggerEvent ?? '',
      parsed.payload ?? {},
    );
  } catch (error) {
    // Controlled 5xx (no stack leak) → Cal.com retries the delivery.
    console.error('cal-webhook: upsert failed', error);
    return jsonResponse(500, { error: 'internal error' });
  }
};

export default defineLogicFunction({
  universalIdentifier: '2b075ac4-54a7-451e-80ab-727c177d2f8c',
  name: 'cal-webhook',
  description:
    'Receives Cal.com booking webhooks (signed), then upserts a Booking keyed by calBookingUid and links the attendee Person.',
  timeoutSeconds: 30,
  httpRouteTriggerSettings: {
    path: '/cal/webhook',
    httpMethod: 'POST',
    isAuthRequired: false,
    forwardedRequestHeaders: [SIGNATURE_HEADER, 'content-type'],
  },
  handler,
});
